### ISSUE TITLE
Crash start

### ISSUE THREAD

**Issue by t-starks** [nicholass003/TopStats#1]
[03:36:44.940] [Server thread/CRITICAL]: nicholass003\topstats\libs\DaPigGuy\libPiggyEconomy\exceptions\MissingProviderDependencyException: "Dependencies for provider bedrockeconomy not found." (EXCEPTION) in "plugins/TopStats.phar/src/nicholass003/topstats/libs/DaPigGuy/libPiggyEconomy/libPiggyEconomy" at line 57
--- Stack trace ---
  #0 plugins/TopStats.phar/src/nicholass003/topstats/TopStats(78): nicholass003\topstats\libs\DaPigGuy\libPiggyEconomy\libPiggyEconomy::getProvider(array[1])
  #1 pmsrc/src/plugin/PluginBase(119): nicholass003\topstats\TopStats->onEnable()
  #2 pmsrc/src/plugin/PluginManager(454): pocketmine\plugin\PluginBase->onEnableStateChange(true)
  #3 pmsrc/src/Server(1404): pocketmine\plugin\PluginManager->enablePlugin(object nicholass003\topstats\TopStats#49601)
  #4 pmsrc/src/Server(1035): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#50212)
  #5 pmsrc/src/PocketMine(355): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#2, object pocketmine\utils\MainLogger#6, string[16] /home/container/, string[24] /home/container/plugins/)
  #6 pmsrc/src/PocketMine(378): pocketmine\server()
  #7 /home/container/PocketMine-MP.phar(168): require(string[72] phar:///tmp/PocketMine-MP-phar-cache.0/PMMPa3rrNZ.tar/src/PocketMine.php)
--- End of exception information ---

**Comment by nicholass003** [comment]
please use BedrockEconomy from cooldogedev or EconomyAPI from onebone at poggit

**Comment by t-starks** [comment]
> onebon

I am using EconomiAPI :c I didn't find the poggit link
