### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Frej111** [nicholass003/TopStats#2]
Hello. When using the MultiWorld plugin, the flying text stays in place and doesn't disappear anywhere. For example, the top stats are in the world file, and when I want to go to world20 via the MultiWorld plugin, the text doesn't disappear

**Comment by nicholass003** [comment]
> Hello. When using the MultiWorld plugin, the flying text stays in place and doesn't disappear anywhere. For example, the top stats are in the world file, and when I want to go to world20 via the MultiWorld plugin, the text doesn't disappear

yes, that's right, that's because TextModel uses FloatingTextParticle from PocketMine-MP, maybe in the next update TextModel will use Entity to avoid duplicates.

**Comment by nicholass003** [comment]
this issue should have been fixed from the change https://github.com/nicholass003/TopStats/commit/0583c3736a2ed8ae2a67b05ac1221d89cbaea6a2
thankyou for your contribution! ❤️
