### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Frej111** [nicholass003/TopStats#3]
Hello. When you go to another world and then back to the world where the tops are, then they are not updated, and you have to restart the server...

**Comment by nicholass003** [comment]
> Hello. When you go to another world and then back to the world where the tops are, then they are not updated, and you have to restart the server...

Hello, can you provide the video, and which version are you using?

**Comment by Frej111** [comment]
Can I have your Discord?

**Comment by nicholass003** [comment]
> Can I have your Discord? 0.3.1

you can join to our discord 
https://discord.gg/EEJK2vxtCp

**Comment by nicholass003** [comment]
i've checked with the latest development version and i don't see any of the problems you describe, i'll close this issue and thank you for providing the information! try using the latest development version at poggit https://poggit.pmmp.io/ci/nicholass003/TopStats/TopStats

if you find a new problem, don't hesitate to reopen it or create a new issue!😁
