### ISSUE TITLE
[Request] Add example command usage

### ISSUE THREAD

**Issue by LalyBad** [nicholass003/TopStats#6]
can you please give example cmd for making top online-time for top 10 players which is a floating txt?

also sorry if I wrote it bad because my english has sucked ty.

**Comment by nicholass003** [comment]
Thank you for creating this issue! I also see that many TopStats users don't know how to use it, now a video tutorial has been made on README.md, I hope it can help! Don't hesitate to ask and don't forget to join the discord server to get answers faster!

- Added in commit : https://github.com/nicholass003/TopStats/commit/b61658a74d4168cbbf8a6a8075d2133ec6d24254
